### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by yyx990803** [vuejs/it.vuejs.org#2]
Edit this line to point to this repo: https://github.com/vuejs/it.vuejs.org/blob/master/_config.yml#L100
Edit the CNAME file: https://github.com/vuejs/it.vuejs.org/blob/master/src/CNAME

Then:
1. Make sure to have the main Vue repo in a sibling folder of the docs repo; (necessary during build script)
2. `make deploy`.

It should then be available at http://vuejs.github.io/it.vuejs.org/ but with broken asset links (because of the path) - I will then point the `it.vuejs.org` domain to it.

**Comment by ludo237** [comment]
Ok I'm going to fix it ASAP today.

**Comment by ludo237** [comment]
@yyx990803 Done, almost. I've cloned the vue repo close to the it.vue.js repository but the Deployment fails because it cannot find the specs.js file.

Inside the Vue repository there's `vue/test/unit/specs/specs.js` but the make file is trying to do this instead
`cp ../vue/test/unit/specs/index.js` but no index.js are provided inside the specs folder

**Comment by yyx990803** [comment]
Hmm, not sure why, but I just cloned the repo and it worked for me. Did you run `npm install` in the vue repo before running the makefile?

**Comment by yyx990803** [comment]
I've created the DNS record, and it should go live in a few hours :)

**Comment by ludo237** [comment]
thx, sorry @yyx990803 first time in a full JS env.
