### ISSUE TITLE
Errors everywhere

### ISSUE THREAD

**Issue by matteocontrini** [vuejs/it.vuejs.org#5]
The translation is full of errors. I've just looked at some commits and there parts that have serious problems.
Example:
https://github.com/vuejs/it.vuejs.org/blob/master/src/api/index.md#metodos

What is `metodos` even? It's not Italian and it shouldn't even be translated!

Also, typos everywhere and non-sense translations: https://github.com/vuejs/it.vuejs.org/commit/5af18cf6af74e5a360fa6e3d8bffaa2fce66ca4a#diff-3daa0e2a8140c5d90e8f6ed3d938c593R1882

**Comment by yyx990803** [comment]
Hmm, I don't understand Italian at all so I think @ludo237 should look into this.

On the other hand, you are more than welcome to submit PRs to fix these problems.

**Comment by ludo237** [comment]
Full of errors? I've review the entire doc with some colleague before publish the first draft, yes errors happen, it's the nature of human.

We are talking about one single `s` in metodos (method in english)

Instead of blaming, and opening 4 issues to say the same thing, you can simple remove the `s` and submit a pull request.

**Comment by matteocontrini** [comment]
Well it's not just that. There are many other wrong parts elsewhere. And "metodo" should even be translated. It should stay "methods".

I was just expecting a serious Italian translation, because seriously there are words that don't even exist now.

**Comment by ludo237** [comment]
I repeat. Errors happen, it's the nature of software.

The concept of "Community Driven" software is that people spot bugs and help fix them not blaming the only guy who's trying to help the fast growing community of VueJs.

I've already fix a lot of bugs yesterday, I'll do a personal review and I'll write a contributing guide because, to be honest, this kind of issues are a waste of the little time I've to fix all the problems.

**Comment by mauroartizzu** [comment]
Matteo: this is the only one italian translation in here. @ludo237 did a great job translating the whole thing alone. The purpose of github is to collaborate, which I am, time permitting. As he said fork the repo and fix the bugs. Some words must be translated, method is metodo in every italian programming language book I've read. Some should not be translated, as keywords of course.

But you can't expect to leave untranslated every word on a tech manual because it would be unreadable.

**Comment by matteocontrini** [comment]
I believe in quality other than going forward.

And I haven't accused anyone :) I've looked at the source code and some
commits and I noticed that the quality of the translations is really low,
and I thought I could report it with some suggestions, and that's what I
did.
My idea was/is that the translation is far from being ready and accurate.

Of course I know what a community is, and I'll be happy to contribute as a
Vue.js user when I'll have enough time.

If you think the issues I've reported are just minor issue, I'm sorry to
say that my concept of quality is a lot different ;)

## 

Matteo
Il 07/mar/2016 10:51, "Claudio Ludovico" notifications@github.com ha
scritto:

**Comment by matteocontrini** [comment]
@mauroartizzu some keywords were translated and I reported that thing, in fact :)
